-- Create schema for the application
CREATE SCHEMA IF NOT EXISTS cybersecurity_awareness;

-- Switch to the new schema
USE cybersecurity_awareness;
-- Create table for storing quiz questions
CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question_text TEXT NOT NULL,
    correct_option VARCHAR(255) NOT NULL
);

-- Create table for storing quiz results
CREATE TABLE IF NOT EXISTS quiz_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    score INT NOT NULL
);

-- Create table for storing contact messages
CREATE TABLE IF NOT EXISTS contact_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    CONSTRAINT chk_email CHECK (email LIKE '%@%')
);

-- Create table for storing feedback
CREATE TABLE IF NOT EXISTS feedback (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    feedback TEXT NOT NULL,
    CONSTRAINT chk_feedback_length CHECK (CHAR_LENGTH(feedback) > 0)
);
-- Insert sample quiz questions
INSERT INTO questions (question_text, correct_option) VALUES
('What is AI in cybersecurity primarily used for?', 'Anomaly detection'),
('What does AI stand for?', 'Artificial Intelligence'),
('Which algorithm is commonly used in AI for cybersecurity?', 'Neural Networks'),
('What is the main advantage of using AI in threat detection?', 'Real-time analysis'),
('How does AI enhance vulnerability management?', 'Automated prioritization'),
('What type of machine learning is used to detect malware?', 'Supervised learning'),
('Which AI technique helps in identifying phishing attacks?', 'Natural Language Processing'),
('What is a common application of AI in cybersecurity?', 'Intrusion Detection Systems'),
('How can AI help in automated incident response?', 'By isolating infected systems'),
('Which algorithm is used for predictive analysis in cybersecurity?', 'Regression Analysis'),
('What is the role of AI in network traffic analysis?', 'Pattern recognition'),
('How does AI contribute to security automation?', 'By executing predefined responses'),
('What is a key benefit of AI in handling zero-day threats?', 'Early detection'),
('How can AI improve endpoint security?', 'Behavioral analysis'),
('What does AI use to enhance threat intelligence?', 'Big data analytics'),
('What is a challenge of integrating AI into cybersecurity?', 'False positives'),
('How does AI assist in analyzing security logs?', 'Automated parsing'),
('What type of AI model is used for anomaly detection?', 'Unsupervised learning'),
('What is the role of AI in data encryption?', 'Enhancing encryption algorithms'),
('Which AI technique is used to combat ransomware?', 'Behavioral prediction'),
('How can AI help with network segmentation?', 'Automated configuration'),
('What is an AI-powered tool for managing security incidents?', 'Security Information and Event Management (SIEM)'),
('How does AI aid in managing security policies?', 'Policy enforcement'),
('What aspect of AI is crucial for threat hunting?', 'Real-time data processing'),
('Which type of AI is used for automating compliance checks?', 'Machine learning'),
('What is a key feature of AI-driven threat detection systems?', 'Adaptive learning'),
('How can AI enhance user authentication processes?', 'By detecting anomalies in login patterns'),
('What is the primary use of AI in data loss prevention?', 'Monitoring and response'),
('How does AI improve phishing detection?', 'By analyzing email content'),
('What is the benefit of AI in vulnerability scanning?', 'Speed and accuracy'),
('How can AI help in fraud detection?', 'Pattern recognition in transactions'),
('What is a common challenge in AI-based cybersecurity solutions?', 'Integration with existing systems'),
('How does AI assist in managing security alerts?', 'Prioritization and categorization'),
('What is a significant advantage of AI in network security?', 'Scalability'),
('How can AI be used in security policy management?', 'Automated updates'),
('What is a common use of AI in endpoint protection?', 'Threat intelligence integration'),
('How does AI support compliance monitoring?', 'Automated reporting'),
('What role does AI play in incident forensics?', 'Data analysis'),
('How can AI help in securing cloud environments?', 'Threat detection and response'),
('What is a primary benefit of AI in cybersecurity threat analysis?', 'Reduced response time'),
('How can AI enhance vulnerability assessments?', 'Automated scanning and analysis'),
('What is an example of AI application in data security?', 'Encryption key management'),
('How does AI improve response to denial-of-service attacks?', 'Traffic analysis and mitigation'),
('What is a key advantage of using AI in security operations?', 'Efficiency in threat management'),
('How can AI contribute to risk assessment?', 'Predictive analytics'),
('What is the role of AI in multi-factor authentication?', 'Enhancing security protocols'),
('How does AI aid in detecting insider threats?', 'Behavioral monitoring'),
('What is a common AI approach for securing applications?', 'Static and dynamic analysis');

-- Insert sample quiz results
INSERT INTO quiz_results (user_name, score) VALUES
('John Doe', 85),
('Jane Smith', 90),
('Michael Brown', 78),
('Emily Davis', 92),
('Daniel Wilson', 88),
('Sophia Martinez', 76),
('James Anderson', 81),
('Olivia Taylor', 94),
('William Thomas', 89),
('Isabella Harris', 83),
('Alexander Clark', 77),
('Mia Lewis', 95),
('Ethan Walker', 82),
('Ava Scott', 90),
('Benjamin Young', 79),
('Charlotte King', 91),
('Henry Wright', 80),
('Amelia Robinson', 87),
('Lucas Walker', 84),
('Harper Hall', 96),
('Sebastian Allen', 79),
('Ella Moore', 86),
('Jack Adams', 91),
('Liam Nelson', 93),
('Aria Carter', 80),
('Mason Roberts', 82),
('Lily Gonzalez', 90),
('Noah Mitchell', 85),
('Zoe Lee', 88),
('Daniel Thompson', 92),
('Grace White', 87),
('Jayden King', 81),
('Chloe Harris', 83),
('Matthew Lee', 90),
('Samantha Collins', 84),
('David Young', 78),
('Natalie Campbell', 95),
('Andrew Cooper', 79),
('Hannah Sanchez', 94),
('Elijah Murphy', 76),
('Eleanor Evans', 92),
('Jacob Turner', 87),
('Ella Harris', 89),
('Ryan Clark', 81),
('Avery Morris', 90),
('Isaiah Ramirez', 82),
('Mila Barnes', 84);

-- Insert sample contact messages
INSERT INTO contact_messages (name, email, message) VALUES
('Alice Johnson', 'alice@example.com', 'I would like more information about your services.'),
('Bob Brown', 'bob@example.com', 'How can I get started with your platform?'),
('Carol White', 'carol@example.com', 'Do you offer training sessions?'),
('David Black', 'david@example.com', 'Can you provide a demo of your product?'),
('Eve Green', 'eve@example.com', 'What are your pricing options?'),
('Frank Blue', 'frank@example.com', 'I have a question about your data protection policies.'),
('Grace Gray', 'grace@example.com', 'Are there any upcoming webinars?'),
('Henry Gold', 'henry@example.com', 'How can I integrate your solution with my existing systems?'),
('Ivy Purple', 'ivy@example.com', 'Can you help with compliance issues?'),
('Jack Red', 'jack@example.com', 'What are the main features of your software?'),
('Karen Orange', 'karen@example.com', 'I need technical support for your product.'),
('Leo Cyan', 'leo@example.com', 'How can I schedule a consultation?'),
('Mia Indigo', 'mia@example.com', 'Do you offer custom solutions?'),
('Noah Brown', 'noah@example.com', 'What is the best way to get started?'),
('Olivia Silver', 'olivia@example.com', 'I would like to discuss partnership opportunities.'),
('Paul Gold', 'paul@example.com', 'Can you provide a case study?'),
('Quinn Blue', 'quinn@example.com', 'How do I get a trial version of your software?'),
('Rachel Green', 'rachel@example.com', 'What is the typical implementation time?'),
('Steve Black', 'steve@example.com', 'I’m interested in your cybersecurity assessments.'),
('Tracy White', 'tracy@example.com', 'Can you provide more details about your encryption methods?'),
('Ursula Yellow', 'ursula@example.com', 'What kind of support do you offer?'),
('Victor Red', 'victor@example.com', 'How do I contact your sales team?'),
('Wendy Brown', 'wendy@example.com', 'Do you have any customer testimonials?'),
('Xander Blue', 'xander@example.com', 'Can you help with integration into my current systems?'),
('Yvonne Gray', 'yvonne@example.com', 'What are your data backup procedures?'),
('Zachary Black', 'zachary@example.com', 'I have questions about your user training programs.'),
('Aiden Green', 'aiden@example.com', 'How do you handle data breaches?'),
('Bella White', 'bella@example.com', 'What security standards do you follow?'),
('Cody Gold', 'cody@example.com', 'How can I become a reseller?'),
('Daisy Blue', 'daisy@example.com', 'What are the benefits of your advanced features?'),
('Ethan Gray', 'ethan@example.com', 'Can you help with risk assessment?'),
('Fiona Brown', 'fiona@example.com', 'Do you offer any guarantees on your products?'),
('George Green', 'george@example.com', 'How do I access your support portal?'),
('Hannah Black', 'hannah@example.com', 'Can you provide a product brochure?'),
('Ian Blue', 'ian@example.com', 'What are the installation requirements for your software?'),
('Julia White', 'julia@example.com', 'Do you offer discounts for bulk purchases?'),
('Kevin Green', 'kevin@example.com', 'How does your solution integrate with cloud services?'),
('Laura Brown', 'laura@example.com', 'Can you provide a list of your clients?'),
('Mike Gray', 'mike@example.com', 'How often do you update your software?'),
('Nina Blue', 'nina@example.com', 'Do you offer personalized training?'),
('Oliver Green', 'oliver@example.com', 'What is your customer support availability?'),
('Paula White', 'paula@example.com', 'Can you provide a comparison with other solutions?'),
('Quinn Brown', 'quinn@example.com', 'How secure is your product?'),
('Rachel Black', 'rachel@example.com', 'What are your data handling procedures?'),
('Sam Green', 'sam@example.com', 'Do you offer consulting services?'),
('Tina White', 'tina@example.com', 'How do you handle software updates?'),
('Ulysses Gray', 'ulysses@example.com', 'Can you provide a demo environment?'),
('Vera Black', 'vera@example.com', 'What are the steps for onboarding?'),
('Walter Green', 'walter@example.com', 'How do you ensure data privacy?');

-- Insert sample feedback
INSERT INTO feedback (name, email, feedback) VALUES
('Charlie Davis', 'charlie@example.com', 'Great platform with helpful resources!'),
('Dana Lee', 'dana@example.com', 'I found the quiz to be very informative.'),
('Ella Brown', 'ella@example.com', 'The training materials are comprehensive.'),
('Frank White', 'frank@example.com', 'The interface is user-friendly and intuitive.'),
('Grace Green', 'grace@example.com', 'The quizzes are challenging and engaging.'),
('Henry Black', 'henry@example.com', 'I appreciate the detailed explanations provided.'),
('Ivy Blue', 'ivy@example.com', 'The feedback after quizzes is very useful.'),
('Jack Red', 'jack@example.com', 'I found the interactive elements to be very effective.'),
('Karen Gray', 'karen@example.com', 'The content is relevant and up-to-date.'),
('Leo Yellow', 'leo@example.com', 'The platform is easy to navigate.'),
('Mia White', 'mia@example.com', 'I enjoyed the simulations and real-world scenarios.'),
('Noah Black', 'noah@example.com', 'The quizzes provide a good assessment of knowledge.'),
('Olivia Blue', 'olivia@example.com', 'The graphics and design are appealing.'),
('Paul Green', 'paul@example.com', 'I would like to see more advanced topics covered.'),
('Quinn Red', 'quinn@example.com', 'The interactive features are very helpful.'),
('Rachel White', 'rachel@example.com', 'The information is presented clearly and concisely.'),
('Steve Black', 'steve@example.com', 'I appreciate the thorough coverage of topics.'),
('Tracy Blue', 'tracy@example.com', 'The platform meets my learning needs effectively.'),
('Ursula Green', 'ursula@example.com', 'The quizzes are well-structured and informative.'),
('Victor Red', 'victor@example.com', 'I like the variety of content offered.'),
('Wendy Black', 'wendy@example.com', 'The feedback provided after quizzes is very helpful.'),
('Xander Blue', 'xander@example.com', 'The user experience is excellent.'),
('Yvonne Green', 'yvonne@example.com', 'I find the content to be highly relevant.'),
('Zachary White', 'zachary@example.com', 'The platform is a great resource for learning.'),
('Aiden Red', 'aiden@example.com', 'The interactive elements enhance the learning experience.'),
('Bella Black', 'bella@example.com', 'The course material is well-organized.'),
('Cody Blue', 'cody@example.com', 'I appreciate the detailed quizzes.'),
('Daisy Green', 'daisy@example.com', 'The platform is engaging and educational.'),
('Ethan White', 'ethan@example.com', 'The quizzes are a great way to test knowledge.'),
('Fiona Black', 'fiona@example.com', 'The content is very comprehensive.'),
('George Blue', 'george@example.com', 'I would like to see more case studies included.'),
('Hannah Green', 'hannah@example.com', 'The platform provides excellent resources for learning.'),
('Ian White', 'ian@example.com', 'The interactive features are very effective.'),
('Julia Black', 'julia@example.com', 'The content is relevant and well-presented.'),
('Kevin Green', 'kevin@example.com', 'The platform is very user-friendly.'),
('Laura Blue', 'laura@example.com', 'I find the quizzes to be very useful for practice.'),
('Mike Black', 'mike@example.com', 'The training materials are of high quality.'),
('Nina Green', 'nina@example.com', 'The feedback after quizzes is very informative.'),
('Oliver White', 'oliver@example.com', 'The interactive features make learning more engaging.'),
('Paula Black', 'paula@example.com', 'I appreciate the well-organized content.'),
('Quinn Green', 'quinn@example.com', 'The platform is a valuable learning tool.'),
('Rachel Blue', 'rachel@example.com', 'The course material is highly useful.'),
('Sam Black', 'sam@example.com', 'The platform provides a comprehensive learning experience.'),
('Tina Green', 'tina@example.com', 'The quizzes are well-constructed and challenging.'),
('Ulysses White', 'ulysses@example.com', 'I would like to see more interactive elements.'),
('Vera Black', 'vera@example.com', 'The content is engaging and educational.'),
('Walter Green', 'walter@example.com', 'The platform is easy to use and navigate.');
